name: Deploy Bot

on: push

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: SFTP Upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ptr-r03.fsn1.purplehosting.fr
        username: sn3ue5zn.7947bcb9
        password: ${{secrets.FTP_PASSWORD}}
        port: 2022
        uploads: |
          ./ => ./
        ignore: |
          *.git
          */**/*git*
          ./.vscode
          ./.github
    - name: Pterodactyl-Restart
      uses: supercrafter100/Pterodactyl-Restart@v1.0
      with:
        PTE_PANEL_URL: 'https://purpleboard.fr'
        PTE_BEARER_TOKEN: ${{ secrets.PTE_BEARER_TOKEN }}
        PTE_PANEL_ID: '7947bcb9'
          
